language: python
python:
    - 3.5
addons:
  apt:
    packages:
      - apache2
      - apache2-dev

before_install:
  - pip install coveralls
  - openssl aes-256-cbc -K $encrypted_af2efcded6c5_key -iv $encrypted_af2efcded6c5_iv -in deploy_github_netapp.enc -out deploy_github_netapp -d
env:
  global:
    - ENCRYPTION_LABEL: "af2efcded6c5"
    - COMMIT_AUTHOR_EMAIL: "albin.stjerna@cern.ch"
install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install mod_wsgi-httpd
  - APXS=~/virtualenv/python3.5/bin/mod_wsgi-apxs pip install mod_wsgi
  - python setup.py install
  - npm install -g spectacle-docs
script:
  - make lint
  - make test
after_success:
  - coveralls
  - make doc_deploy
