language: python
cache:
  pip: true
  directories:
      - .hypothesis
python:
    - 3.5
addons:
  apt:
    packages:
      - apache2
      - apache2-dev

before_install:
  - pip install coveralls
  - nvm install stable
  - nvm use stable
env:
  - ENCRYPTION_LABEL: "af2efcded6c5"
  - COMMIT_AUTHOR_EMAIL: "albin.stjerna@cern.ch"
install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install mod_wsgi-httpd
  - APXS=~/virtualenv/python3.5/bin/mod_wsgi-apxs pip install mod_wsgi
  - python setup.py install
  - npm install -g spectacle-docs
script:
  - make lint
  - make test
after_success:
  - coveralls
  - make doc_deploy
