language: python
python:
    - 3.5
addons:
  apt:
    packages:
      - apache2
      - apache2-dev
install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install mod_wsgi-httpd
  - APXS=~/virtualenv/python3.5/bin/mod_wsgi-apxs pip install mod_wsgi
  - python setup.py install
script:
  - make lint
