language: python
python:
    - 3.5
addons:
  apt:
    packages:
    - httpd
    - httpd-tools
    - httpd-devel
script:
    - pip install -r requirements.pip
    - pip install mod_wsgi-httpd
    - APXS=~/virtualenv/python3.5/bin/mod_wsgi-apxs pip install mod_wsgi
    - python setup.py install
